version: '3'

services:

  proxy:
    image: nginx:1.11.8-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./resources/nginx.conf:/etc/nginx/nginx.conf"
      - "./resources/conf.d:/etc/nginx/conf.d"
      - "./resources/ssl:/etc/nginx/ssl"
