version: '3'

services:

  yc5-app:
    build: ./nginx-php
    image: my/yc5-app:5.0
    container_name: yc5-app
    ports:
      - "80:80"
    volumes:
      - "web-data:/usr/share/nginx/html/data"
    depends_on:
      - yc5-db

  yc5-db:
    build: ./mysql
    image: my/yc5-db:5.5.54
    container_name: yc5-db
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: yc5
      MYSQL_ROOT_PASSWORD: team
      MYSQL_USER: team
      MYSQL_PASSWORD: team

volumes:
  web-data: 
  db-data:
