version: "3"

services:
  app:
    build: .
    image: myapp:1.0
    container_name: app
    volumes:
      - tomcat-dir:/tmp
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILE_ACTIVE=

volumes:
  tomcat-dir:
