version: '3'

services:

  nginx:
    build: ./nginx
    image: my/nginx:1.11.8-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/html:/usr/share/nginx/html"

  tomcat:
    build: ./tomcat
    image: my/tomcat:8.5.11-jre8-alpine
    container_name: tomcat
    ports:
      - "8080:8080"

  mariadb:
    build: ./mariadb
    image: my/mariadb:10.1.20
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

volumes:
  dbdata:
