- name: Pre-required packages are present
  apt: 
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Docker repository gpg key is imported
  apt_key:
    url: "https://yum.dockerproject.org/gpg"

- name: Docker repository is added and cache is updated
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ubuntu_version }} {{ release }}"
    update_cache: yes

- name: Docker Engine is present
  apt:
    name: docker-engine
    update_cache: yes
    force: yes
    state: latest

- name: User is added to the docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes


- name: Docker-compose executable is present
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
